Repository mesosphere/kubeaddons-enterprise, pull requests merged in 2020-02, with the labels that each got.

#17 add overview of Kafka/Zk and add default monitor param
  addons/kafka/1.x/kafka-2.yaml
  metadata/static/kafka/overview.md
  metadata/static/zookeeper/overview.md
Labels: ready

#21 Add Cassandra
  addons/cassandra/0.x/cassandra.yaml
  metadata/static/cassandra/logo.svg
  metadata/static/cassandra/overview.md
  test/addons_test.go
  test/groups.yaml
Labels: new-addon, ready

#24 cassandra: add metadata to root.yaml
  metadata/root.yaml
Labels: chore, ready

#19 kafka: require prometheus for monitoring features
  addons/kafka/1.x/kafka-2.yaml
  test/addons_test.go
  test/groups.yaml
Labels: ready

#18 Add Spark add-on
  CODEOWNERS
  addons/spark/0.x/spark-1.yaml
  metadata/root.yaml
  metadata/static/spark/logo.svg
  metadata/static/spark/overview.md
  test/addons_test.go
  test/groups.yaml
Labels: ready

#27 fix appversions and remove zk/kafka old addons
  addons/cassandra/0.x/cassandra.yaml
  addons/kafka/1.x/kafka-1.yaml
  addons/kafka/1.x/kafka-2.yaml
  addons/spark/0.x/spark-1.yaml
  addons/zookeeper/0.x/zookeeper-1.yaml
  addons/zookeeper/0.x/zookeeper-2.yaml
Labels: ready

#29 jenkins.yaml : fix yaml typo for jenkins ingress
  addons/jenkins/1.x/jenkins.yaml
Labels: ready

#32 Spark Operator GA add-on update
  addons/spark/1.x/spark-1.yaml
  metadata/static/spark/overview.md
Labels: ready
